# Generated by Django 3.0.2 on 2020-01-17 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='This field is required!', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='This field is required!', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_login', models.DateTimeField(blank=True, help_text='This field will fill automatically after first login! Non-required!', null=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='This field will fill automatically after every login! Non-required!', null=True)),
                ('first_name', models.CharField(help_text='This field is required!', max_length=50)),
                ('last_name', models.CharField(help_text='This field is required!', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='This field is required only if role is not Student!', max_length=50, null=True)),
                ('address', models.CharField(help_text='This field is required!', max_length=100)),
                ('city', models.CharField(help_text='This field is required!', max_length=50)),
                ('phone', models.CharField(help_text='This field is required only if role is not Student!', max_length=50)),
                ('salt', models.CharField(default=')xuqD)OSVnY(nR%)qT4W==y-Y kaS1FT', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255)),
                ('admin_password', models.CharField(blank=True, help_text='This password will be encrypted through Django Admin! This field is required!', max_length=255, null=True)),
                ('password', models.CharField(blank=True, help_text="This field shouldn't be used through Django Admin! Non-required!", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('birth_date', models.DateField(help_text='This field is required!')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_book.Gender')),
                ('parent_father', models.ForeignKey(blank=True, help_text='This field is required if role is a Student! Optional if parent_mother is filled!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.parent_father+', to='school_book.User')),
                ('parent_mother', models.ForeignKey(blank=True, help_text='This field is required if role is a Student! Optional if parent_father is filled!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.parent_mother+', to='school_book.User')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_book.Role')),
            ],
        ),
    ]
