# Generated by Django 3.0.2 on 2020-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='This field is required only if role is not a Student!', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='This field is required only if role is not a Student!', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default="rAZeCAf-qH){oxY'KTGq*S>vhVl)=eQ8", help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255),
        ),
    ]
