# Generated by Django 3.0.2 on 2020-01-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0002_auto_20200122_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='pv;&TxJT@;/I<r{!8mF/)Cv$:07%D]nv', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
