# Generated by Django 3.0.2 on 2020-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0005_auto_20200122_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, help_text='This field will be filled automatically when user become deactivated! Field will be deleted when user become activated!', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='(MfXie_ecwYFc:\\oQX?j^l,XH;J0_W`e', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
