# Generated by Django 3.0.2 on 2020-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0006_auto_20200122_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expired_activation_code',
            field=models.DateTimeField(blank=True, help_text='This field will fill automatically! Activation code will not be valid if user uses activation code after one hour! Non-required!', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, help_text='This field will fill automatically when user become deactivated! Field will be deleted when user become activated! Non-required!', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default="FjN-0y.bV*S0OFo+XQ^&'8rWNIv>\\f60", help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
