# Generated by Django 3.0.2 on 2020-01-23 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0007_auto_20200122_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_year', models.CharField(help_text='This field is required!', max_length=9)),
                ('name', models.CharField(help_text='This field is required!', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='If class room is deactivated, professors can only read class room and all related with class room!')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default=".Nq8K7yt3xc`XsA-G0=8Y:5~'j.]5HFE", help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SchoolClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='This field is required!', max_length=50, unique=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_book.SchoolClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_book.User')),
            ],
            options={
                'unique_together': {('student', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClassProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='This field is required!', max_length=50, unique=True)),
                ('professor', models.ForeignKey(blank=True, help_text='This field can be empty, but then user will not be able to write grades, absences, next event (exams), etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.User')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_book.SchoolClass')),
            ],
            options={
                'unique_together': {('professor', 'school_class')},
            },
        ),
    ]
