# Generated by Django 3.0.2 on 2020-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0008_auto_20200123_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclassprofessor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schoolclassstudent',
            name='name',
        ),
        migrations.AddField(
            model_name='schoolclassprofessor',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If professor is deactivated then professor can only read student information!'),
        ),
        migrations.AddField(
            model_name='schoolclassstudent',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If student is deactivated then professor can see only read student information!'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default="cD(62*$A4[SpNly,Bw^x#'>|Q$]-]/7@", help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
