# Generated by Django 3.0.2 on 2020-01-23 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0009_auto_20200123_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, help_text="If school subject is deactivated then that school subject can't be chosen in school class subjects!")),
                ('name', models.CharField(help_text='This field is required!', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='IkC":N)m6TQk/_n5vx^00Lj@no&CR(xn', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
