# Generated by Django 3.0.2 on 2020-01-23 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0010_auto_20200123_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='_Tw9zm$Vy^qtDz1#=Zz2HD7ls#5w]{vk', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ClassRoomSchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, help_text='If school subject is deactivated then that school subject can be readable only!')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.User')),
                ('school_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolSubject')),
            ],
        ),
    ]
