# Generated by Django 3.0.2 on 2020-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0011_auto_20200123_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='S-uX7I^S9O2ahz~n-:Wc"ORkwK)D2-Fd', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classroomschoolsubject',
            unique_together={('professor', 'school_subject')},
        ),
    ]
