# Generated by Django 3.0.2 on 2020-02-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0012_auto_20200123_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomschoolsubject',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='8pALUl!k4:/*/}0?DvY?cnPvhxVv1{cG', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
