# Generated by Django 3.0.2 on 2020-02-12 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0013_auto_20200212_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default=',d\\V78E(#..XmpM_< i\\9T; TBwiy7"p', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField(help_text='Professor can enter grades in range 1-5.')),
                ('grade_type', models.CharField(help_text='Professor can enter some type e.g exam.', max_length=50)),
                ('comment', models.CharField(blank=True, help_text="This is additional field to set some notes e.g Student didn't learn last lesion!", max_length=128, null=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.professor+', to='school_book.User')),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolClass')),
                ('school_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolSubject')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.student+', to='school_book.User')),
            ],
            options={
                'unique_together': {('professor', 'school_subject')},
            },
        ),
    ]
