# Generated by Django 3.0.2 on 2020-02-12 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0014_auto_20200212_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='3J?*I/|n{1#J3}RmFQK2D1Y~A??\\r?qF', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='Professor will use this field to set title of event, e.g exam, excursion etc.', max_length=64)),
                ('comment', models.CharField(help_text='Here professors add new events that parents could see and motivate their children to get better results! E.g. Math exam in 13.02.2020 in 13:00:00 or Math exam will benext friday or this field could be as some school events like excursion etc.', max_length=128)),
                ('date', models.DateTimeField()),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.User')),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolClass')),
            ],
        ),
    ]
