# Generated by Django 3.0.2 on 2020-02-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0015_auto_20200212_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='school_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolSubject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='rksf+;m=/"</Hk-bO[Q`pCs8G\\{h)!\\U', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
