# Generated by Django 3.0.2 on 2020-02-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0016_auto_20200212_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomschoolsubject',
            name='school_class',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='classroomschoolsubject',
            name='professor',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.User'),
        ),
        migrations.AlterField(
            model_name='classroomschoolsubject',
            name='school_subject',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolSubject'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.CharField(help_text='Here professors add new events that parents could see and motivate their children to get better results! E.g. Math exam in 13.02.2020 in 13:00:00 or Math exam will benext friday or this field could be as some school events like excursion etc. This field is required!', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='This field is required!'),
        ),
        migrations.AlterField(
            model_name='event',
            name='professor',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='school_class',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='event',
            name='school_subject',
            field=models.ForeignKey(help_text='This field is optional! This field will help parents to know if event is exam andwhich school subject is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolSubject'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Professor will use this field to set title of event, e.g exam, excursion etc. This field is required!', max_length=64),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.CharField(blank=True, help_text="This is additional field to set some notes e.g Student didn't learn last lesion! Not required!", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(help_text='Professor can enter grades in range 1-5. Required!'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(help_text='Professor can enter some type e.g exam. Required!', max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='professor',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.professor+', to='school_book.User'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school_class',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school_subject',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolSubject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.student+', to='school_book.User'),
        ),
        migrations.AlterField(
            model_name='schoolclassprofessor',
            name='professor',
            field=models.ForeignKey(blank=True, help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.User'),
        ),
        migrations.AlterField(
            model_name='schoolclassprofessor',
            name='school_class',
            field=models.ForeignKey(help_text='This field is required!', on_delete=django.db.models.deletion.CASCADE, to='school_book.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='schoolclassstudent',
            name='school_class',
            field=models.ForeignKey(help_text='This field is required!', on_delete=django.db.models.deletion.CASCADE, to='school_book.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='schoolclassstudent',
            name='student',
            field=models.ForeignKey(help_text='This field is required!', on_delete=django.db.models.deletion.CASCADE, to='school_book.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default="$TBn9lgR='!,<M68drjO~IV9f$5:~in$", help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classroomschoolsubject',
            unique_together={('professor', 'school_subject', 'school_class')},
        ),
        migrations.RemoveField(
            model_name='classroomschoolsubject',
            name='class_room',
        ),
    ]
