# Generated by Django 3.0.2 on 2020-02-13 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0017_auto_20200212_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='6XT}HSK5f\'&<!s;`g$).2I8"5\'*K.t!!', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, help_text='This filed will help parents to have a better view. Not required!', max_length=64, null=True)),
                ('comment', models.CharField(help_text='Professor needs enter a reason of absence. E.g. student did not show up. Required!', max_length=128)),
                ('is_justified', models.BooleanField(blank=True, help_text='This field will help professors and parents to see is some absence justified. Not required!', null=True)),
                ('professor', models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.professor+', to='school_book.User')),
                ('school_class', models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolClass')),
                ('school_subject', models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_book.SchoolSubject')),
                ('student', models.ForeignKey(help_text='This field is required!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.student+', to='school_book.User')),
            ],
        ),
    ]
