# Generated by Django 3.0.2 on 2020-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_book', '0018_auto_20200213_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='is_justified',
            field=models.BooleanField(default=False, help_text='This field will help professors and parents to see is some absence justified. Not required!'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default=';4]]<2o:8&}z#gelIZC]67`y#hffE^eL', help_text='This field is self generated! Do not change it through Django Admin. Required!', max_length=255, null=True),
        ),
    ]
